<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFrameworks>$(ProjectTargetFrameworks)</TargetFrameworks>
        <IsPackable>false</IsPackable>
    </PropertyGroup>
    
    <ItemGroup>
      <PackageReference Include="Messager.NET.Microsoft.DependencyInjection" Version="1.0.0" />
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="11.0.0-rc.1.26425.128" />
    </ItemGroup>
</Project>
