<Project>

    <PropertyGroup>
        <ProjectTargetFrameworks>net10.0;net11.0</ProjectTargetFrameworks>
        <ProjectVersion>1.0.1</ProjectVersion>
        <ProjectAssemblyVersion>1.0.0.1</ProjectAssemblyVersion>
        <ProjectAuthors>NovoDwarf</ProjectAuthors>
        <ProjectCopyright>NovoDwarf</ProjectCopyright>
        <ProjectRepositoryUrl>https://github.com/NovoDwarf/MathForge</ProjectRepositoryUrl>
    </PropertyGroup>

    <PropertyGroup>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup Condition="'$(IsPackable)' != 'false'">
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Authors>$(ProjectAuthors)</Authors>
        <Copyright>$(ProjectCopyright)</Copyright>
        <PackageProjectUrl>$(ProjectRepositoryUrl)</PackageProjectUrl>
        <RepositoryUrl>$(ProjectRepositoryUrl)</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
    </PropertyGroup>
    
    <PropertyGroup Condition="'$(MSBuildProjectName)' == 'Messager.NET.Core'">
        <Title>Messager.NET.Core</Title>
        <Description>Core contracts for Messager.NET.</Description>
    </PropertyGroup>

    <PropertyGroup Condition="'$(MSBuildProjectName)' == 'Messager.NET'">
        <Title>Messager.NET</Title>
        <Description>Runtime implementation for Messager.NET.</Description>
    </PropertyGroup>
    
    <PropertyGroup Condition="'$(MSBuildProjectName)' == 'Messager.NET.Microsoft.DependencyInjection'">
        <Title>Messager.NET.Microsoft.DependencyInjection</Title>
        <Description>Microsoft.Extensions.DependencyInjection integration for Messager.NET.</Description>
    </PropertyGroup>

    <PropertyGroup Condition="'$(MSBuildProjectName)' == 'Messager.NET.Autofac'">
        <Title>Messager.NET.Autofac</Title>
        <Description>Autofac integration for Messager.NET.</Description>
    </PropertyGroup>

</Project>
