<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TargetFrameworks>$(MessagerSupportedTargetFrameworks)</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
      <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="11.0.0" />
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="11.0.0-preview.3.26207.106" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Messager.NET.Autofac\Messager.NET.Autofac.csproj" />
      <ProjectReference Include="..\Messager.NET.Core\Messager.NET.Core.csproj" />
      <ProjectReference Include="..\Messager.NET\Messager.NET.csproj" />
    </ItemGroup>

</Project>
