<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(ProjectTargetFrameworks)</TargetFrameworks>
    </PropertyGroup>
    
    <ItemGroup>
      <PackageReference Include="Messager.NET.Core" Version="1.0.0" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="11.0.0-rc.1.26425.128" />
    </ItemGroup>

</Project>
