<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(ProjectTargetFrameworks)</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Messager.NET.Core\Messager.NET.Core.csproj" />
      <ProjectReference Include="..\Messager.NET\Messager.NET.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Autofac" Version="9.3.2" />
    </ItemGroup>

</Project>
