<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(ProjectTargetFrameworks)</TargetFrameworks>
    </PropertyGroup>
    
    <ItemGroup>
      <PackageReference Include="Autofac" Version="9.3.2" />
      <PackageReference Include="Messager.NET" Version="1.0.0" />
    </ItemGroup>

</Project>
